SELECT a.QUARTER, count(a.QUARTER) as ECOLI_COUNT
FROM (SELECT case when MONTH(DIFFERENTIATION_DATE) < 4 then "1Q" when MONTH(DIFFERENTIATION_DATE) < 7 then "2Q" when MONTH(DIFFERENTIATION_DATE) < 10 then "3Q" else "4Q" end as QUARTER 
FROM ECOLI_DATA) as a
group by QUARTER
order by QUARTER