WITH RENTAL_HISTORY AS (
    SELECT 
        CAR_ID, 
        MONTH(START_DATE) AS MONTH
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
)
, CAR_RENTAL_COUNT AS (
    SELECT 
        MONTH, 
        CAR_ID, 
        COUNT(*) AS RECORDS
    FROM RENTAL_HISTORY
    GROUP BY MONTH, CAR_ID
)
, FILTERED_CARS AS (
    SELECT 
        CAR_ID
    FROM CAR_RENTAL_COUNT
    GROUP BY CAR_ID
    HAVING SUM(RECORDS) >= 5
)
SELECT 
    C.MONTH, 
    C.CAR_ID, 
    C.RECORDS
FROM CAR_RENTAL_COUNT C
JOIN FILTERED_CARS F ON C.CAR_ID = F.CAR_ID
ORDER BY C.MONTH ASC, C.CAR_ID DESC;
