SELECT ID, FISH_NAME, LENGTH
FROM FISH_INFO AS a
JOIN FISH_NAME_INFO AS b ON a.FISH_TYPE = b.FISH_TYPE
WHERE LENGTH = (
    SELECT MAX(LENGTH)
    FROM FISH_INFO AS c
    WHERE c.FISH_TYPE = a.FISH_TYPE
);
