SELECT a.BOOK_ID, b.AUTHOR_NAME, DATE_FORMAT(a.PUBLISHED_DATE,"%Y-%m-%d") as PUBLISHED_DATE
FROM BOOK as a left outer join AUTHOR as b on a.AUTHOR_ID = b.AUTHOR_ID
WHERE a.CATEGORY="경제"
order by PUBLISHED_DATE ASC